from django.contrib import admin
from django.urls import path
from CorintecApp import views
from django.urls import include, path

urlpatterns = [
    path('',views.Login, name='login'),
    path('home/', views.home.as_view(), name='home'),
    path('registrarse/', views.Registrarse, name='registrar'),
    path('carrito/', views.CarritoComprasView.as_view(), name='carrito'),
    path('busqueda/producto', views.BusquedaProductos.as_view(), name='busqueda'),
    path('gestionar/producto', views.GestionarProductos.as_view(), name='gestionar-producto'),
    path('busqueda/cliente', views.ClienteListView.as_view(), name='busqueda-cliente'),
    path('busqueda/distribuidor', views.DistribuidorListView.as_view(), name='busqueda-distribuidor'),
    path('busqueda/pedido', views.PedidoListView.as_view(), name='busqueda-pedido'),
    path('busqueda/factura', views.FacturaListView.as_view(), name='busqueda-factura'),
    path('agregar/cliente', views.AgregarClienteView.as_view(), name='agregar-cliente'),
    path('agregar/distribuidor', views.AgregarDistribuidorView.as_view(), name='agregar-distribuidor'),
    path('agregar/producto', views.AgregarProductosView.as_view(), name='agregar-producto'),
    path('editar/cliente/<int:pk>', views.UpdateCliente.as_view(), name='editar-cliente'),
    path('editar/distribuidor/<int:pk>', views.UpdateDistribuidor.as_view(), name='editar-distribuidor'),
    path('editar/producto/<int:pk>', views.UpdateProducto.as_view(), name='editar-producto'),
    path('registrar/usuario', views.registerusuario, name='registrar-usuario'),
    path('eliminar/cliente/<int:pk>', views.DeleteCliente, name='eliminar-cliente'),
    path('eliminar/distribuidor/<int:pk>', views.DeleteDistribuidor, name='eliminar-distribuidor'),
    path('registrar/administrador', views.RegistrarAdminView.as_view(), name='registrar-administrador'),
    path('registrar/vendedor', views.RegistrarVendedorView.as_view(), name='registrar-vendedor'),
    path('add/carrito/<int:carrito_id>/producto/<int:producto_id>',views.addCarritoCompras.as_view(), name='add-carrito'),
    path('add/carrito/<int:carrito_id>/producto/<int:producto_id>/orden/compra',views.addCarritoComprasOrdenCompra, name='add-carrito-orden-compra'),
    path('remove/carrito/<int:carrito_id>/producto/<int:producto_id>',views.removeCarritoCompras, name='remove-carrito'),
    path('remove/carrito/<int:carrito_id>/producto/<int:producto_id>/orden/compra', views.removeCarritoComprasOrdenCompra,name='remove-carrito-orden-compra'),
    path('clean/carrito/<int:carrito_id>/orden/compra',views.cleanCarritoComprasOrdenCompra, name='clean-carrito-orden-compra'),
    path('actualizar/lista/producto/carrito/<int:carrito_id>/',views.ActualizarFiltroProducto.as_view(), name='actualizar-filtro-producto'),
    path('carrito/<int:carrito_id>/cliente/<int:cliente_id>/facturacion', views.FacturacionView.as_view(), name='facturar-producto'),
    path('carrito/cotizar', views.CotizacionView.as_view(), name='cotizar-producto'),
    path('carrito/<int:carrito_id>/buscar/cliente/', views.FiltrarClienteCotizacion.as_view(), name='filtrar-cliente-cotizacion'),
    path('cotizacion/carrito/<int:carrito_id>/buscar/cliente/', views.FiltrarCliente.as_view(), name='filtrar-cliente'),
    path('ordencompra/buscar/distribuidor/', views.FiltrarDistribuidor.as_view(), name='filtrar-distribuidor'),
    path('ordencompra/', views.OrdenCompraView.as_view(), name='orden-compra'),
    path('ordencompra/distribuidor/<int:distribuidor_id>/buscar/productos', views.FiltarProductos.as_view(), name='filtrar-producto'),
    path('ordencompra/productos/<int:carrito_id>/distribuidor/<int:distribuidor_id>', views.OrdenEnvioFormularioView.as_view(), name='ordencompra-formulario'),
    path('ordencompra/terminar/<int:pk>/usuario/<int:user>', views.TerminateOrdenCompra, name='terminate-ordenCompra'),
    path('ordencompra/cancelar/<int:pk>/usuario/<int:user>', views.CancelOrdenCompra, name='cancel-ordenCompra'),
    path('pedido/<int:pk>/usuario/<int:user>/terminar', views.TerminatePedido, name='terminate-pedido'),
    path('pedido/<int:pk>/usuario/<int:user>/cancelar', views.CancelPedido, name='cancel-pedido'),
    path('carrito/disponibilidad/producto/<int:producto_id>', views.chequearDisponibilidad.as_view(), name='verificar-disponibilidad-producto'),
    path('cotizacion/generar/pdf/cliente/<int:cliente_id>/carrito/<int:carrito_id>', views.GenerateCotizacionPdf, name='cotizacion-pdf'),
    path('facturacion/generar/pdf/factura/<int:factura_id>', views.GenerateFacturaPdf,name='facturacion-pdf'),
    path('actualizar/ventas/<str:t_venta>', views.VentasDashBoard.as_view(), name='venta-dashboard'),
    path('actualizar/productos/agotados', views.ProductoAgotado.as_view(), name='productos-agotados'),
    path('informacion/cliente/<int:cliente_id>', views.InfoCliente, name='info-cliente'),
]